import type { Metadata } from "next";
import { chivo, fira_mono } from './fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chivo.variable + ' ' + fira_mono.variable}>
        <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
          <div className="w-full max-w-md space-y-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
