import type { Metadata } from "next";
import { chivo, fira_mono } from './fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chivo.variable + ' ' + fira_mono.variable}>
        {children}
      </body>
    </html>
  );
}
