/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BeFhZb3Yvcm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Pastebin({ handleSubmit, value, setValue }: {
  handleSubmit: (e: React.FormEvent) => void,
  value: string,
  setValue: (value: string) => void
}) {
  return (
    <>
      <div aria-live="assertive">
        {/* Error messages go here */}
      </div>
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
        <form className="space-y-4" onSubmit={handleSubmit} aria-labelledby="formTitle">
          <h1 id="formTitle" className="text-2xl font-bold mb-4">Pastebin Clone</h1>
          <Textarea
            name="pasteContent"
            aria-label="Paste content"
            className="w-full h-40 resize-none rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 font-mono"
            placeholder="Enter your text here..."
            value={value}
            onChange={(e) => setValue(e.target.value)}
          />
          <Button aria-label="Create paste" className="w-full font-bold" type="submit">
            Create Paste
          </Button>
        </form>
      </div>
    </>
  )
}
