/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BeFhZb3Yvcm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Metadata } from "./metadata"

export function Pastebin() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md space-y-4">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <h1 className="text-2xl font-bold mb-4">Pastebin Clone</h1>
          <form className="space-y-4">
            <Textarea
              className="w-full h-40 resize-none rounded-md border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 font-mono"
              placeholder="Enter your text here..."
            />
            <Button className="w-full font-bold" type="submit">
              Create Paste
            </Button>
          </form>
        </div>
        <Metadata />
      </div>
    </div>
  )
}
